project_name: artifact

before:
  hooks:
  - go get ./...

builds:
  - id: non-windows-build
    env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: windows-build
    env:
    - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.VERSION={{.Tag}}
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - id: non-windows-archive
    builds:
      - non-windows-build
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      linux: Linux
      darwin: Darwin
      amd64: x86_64
      386: i386
  - id: windows-archive
    builds:
      - windows-build
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
      windows: Windows

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
