#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export GOOGLE_APPLICATION_CREDENTIALS=$DIR/../../artifacts-play-84f9d6266402.json
export BUCKET_NAME=artifacts-play-bucket
cd $DIR/..

GCSPATH=myTest/test.sh
export SEMAPHORE_JOB_ID=some_job_id_123
go test ./... && script/run push job -d $GCSPATH script/test && script/run pull job -d test2 $GCSPATH && script/run yank job $GCSPATH && diff script/test test2 && rm test2
