on: [push]
name: Unit tests
jobs:
  unit-testing:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Build
        run: go build -o artifact.exe
      - name: Run tests
        run: |
          gotestsum --format short-verbose --packages="./..." -- -p 1
